services:
  web:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: Hoarder-Web
    network_mode: syno_bridge
    volumes:
      - /volume1/docker/hoarder/data:/data:rw
    ports:
      - 41254:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    restart: on-failure:5
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: Hoarder-Chrome
    network_mode: syno_bridge
    restart: on-failure:5
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: Hoarder-Meili
    network_mode: syno_bridge 
    volumes:
      - /volume1/docker/hoarder/meili:/meili_data:rw   
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
        restart: on-failure:5