services:
  web:
    image: ghcr.io/hoarder-app/hoarder:latest
    container_name: Hoarder-Web
    networks:
      - hoarder_network
    volumes:
      - /volume1/docker/hoarder/data:/data:rw
    ports:
      - 3000:3000
    env_file:
      - stack.env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    restart: on-failure:5
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: Hoarder-Chrome
    networks:
      - hoarder_network
    restart: on-failure:5
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: Hoarder-Meili
    networks:
      - hoarder_network
    volumes:
      - /volume1/docker/hoarder/meili:/meili_data:rw
    env_file:
      - stack.env
    environment:
      MEILI_NO_ANALYTICS: "true"

networks:
  hoarder_network:
    driver: bridge
