services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    mem_limit: 3g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    ports:
      - 3000:3000
    volumes:
      - /volume1/docker/metabase/plugins:/plugins:rw
    env_file: stack.env
    environment:
      TZ: {VALUE}
      JAVA_TIMEZONE: {VALUE}
      MUID: 1026
      MGID: 100
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: {VALUE}
      MB_DB_PASS: {VALUE}
      MB_DB_HOST: postgres-metabase
    restart: on-failure:5
    networks:
      - metabasenet
  postgres:
    image: postgres:latest
    container_name: postgres-metabase
    hostname: postgres-metabase
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/metabase/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: {VALUE}
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: {VALUE}
    restart: on-failure:5
    networks:
      - metabasenet
networks:
  metabasenet:
    driver: bridge
