services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: syno_bridge
    ports:
      - 8787:8787
    env_file: stack.env
    volumes:
      - /volume1/docker/readarr:/config
      - /volume1/data/media/Books:/books #optional
      - /volume1/data/downloads/complete:/downloads #optional
    restart: unless-stopped